tap "oven-sh/bun"
tap "steipete/tap"
brew "bat"
brew "colima"
brew "docker"
brew "eza"
brew "fd"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "go@1.24", link: true
brew "go@1.25"
brew "lazydocker"
brew "lazygit"
brew "libevent"
brew "libuv"
brew "lz4"
brew "mise"
brew "mole"
brew "ncurses"
brew "neovim"
brew "nvm"
brew "ripgrep"
brew "rustup"
brew "starship"
brew "tldr"
brew "tmux"
brew "uv"
brew "yazi"
brew "zoxide"
brew "steipete/tap/remindctl"
cask "alcove"
cask "aldente", args: { appdir: "~/Applications" }
cask "alt-tab"
cask "anki", args: { appdir: "~/Applications" }
cask "app-cleaner"
cask "appcleaner"
cask "bettertouchtool"
cask "bilibili"
cask "chatgpt"
cask "cleanshot", args: { appdir: "~/Applications" }
cask "devtoys", args: { appdir: "~/Applications" }
cask "downie", args: { appdir: "~/Applications" }
cask "easydict", args: { appdir: "~/Applications" }
cask "flux-app"
cask "folo", args: { appdir: "~/Applications" }
cask "font-fira-code"
cask "font-meslo-lg-nerd-font"
cask "goland"
cask "google-chrome", args: { appdir: "~/Applications" }
cask "hammerspoon"
cask "iina", args: { appdir: "~/Applications" }
cask "iterm2", args: { appdir: "~/Applications" }
cask "jordanbaird-ice", args: { appdir: "~/Applications" }
cask "keka", args: { appdir: "~/Applications" }
cask "localsend"
cask "menubarx", args: { appdir: "~/Application" }
cask "motrix"
cask "navicat-premium-lite", args: { appdir: "~/Applications" }
cask "notion"
cask "obsidian"
cask "ollama-app", args: { appdir: "~/Applications" }
cask "one-switch"
cask "onyx"
cask "permute", args: { appdir: "~/Applications" }
cask "picgo", args: { appdir: "~/Applications" }
cask "pycharm"
cask "quitter"
cask "raycast", args: { appdir: "~/Applications" }
cask "rustdesk", args: { appdir: "~/Applications" }
cask "shortcat"
cask "stats"
cask "steam"
cask "steam-plus-plus"
cask "super-productivity"
cask "textmate"
cask "typora", args: { appdir: "~/Applications" }
cask "visual-studio-code", args: { appdir: "~/Applications" }
cask "zed", args: { appdir: "~/Applications" }
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.path-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "golang.go"
vscode "hediet.vscode-drawio"
vscode "humao.rest-client"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.vscode-typescript-next"
vscode "octref.vetur"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "rust-lang.rust-analyzer"
vscode "streetsidesoftware.code-spell-checker"
vscode "tauri-apps.tauri-vscode"
vscode "usernamehw.errorlens"
vscode "vue.volar"
vscode "xabikos.javascriptsnippets"
go "github.com/air-verse/air"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
uv "nano-pdf"
uv "thefuck"
