export ZSH="$HOME/.oh-my-zsh"
export ZSHRC_D="$HOME/.zshrc.d"

ZSH_THEME=""
DISABLE_AUTO_UPDATE="true"
ZSH_DISABLE_COMPFIX="true"

: "${XDG_CACHE_HOME:=$HOME/.cache}"

export ZSH_CACHE_DIR="${ZSH_CACHE_DIR:-$XDG_CACHE_HOME/oh-my-zsh}"
export ZSH_COMPDUMP="${ZSH_COMPDUMP:-$XDG_CACHE_HOME/zsh/.zcompdump-${HOST%%.*}-${ZSH_VERSION}}"

mkdir -p "$ZSH_CACHE_DIR" "${ZSH_COMPDUMP:h}"

typeset -gU path fpath

source_if_readable() {
  [[ -r "$1" ]] || return 0
  source "$1"
}

source_modules() {
  local file

  for file in "$@"; do
    source_if_readable "$ZSHRC_D/$file"
  done
}

source_modules \
  env.zsh \
  env.local.zsh \
  plugins.zsh

if [[ -r "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
fi

source_modules \
  aliases.zsh \
  completion.zsh \
  tools.zsh
